#!/bin/bash
# Build AgentTimeline.app from the SwiftPM package.
# Usage: scripts/build-app.sh [debug|release]   (default: release)
set -euo pipefail

CONFIG="${1:-release}"
PKG_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_NAME="AgentTimeline"
BUILD_DIR="$PKG_DIR/.build/$CONFIG"
OUT_DIR="$PKG_DIR/dist"
APP="$OUT_DIR/$APP_NAME.app"
# 版本单一事实源：仓库根 VERSION（Windows csproj 同源读取；release CI 校验 tag 一致）。
VERSION="$(tr -d '[:space:]' < "$PKG_DIR/../VERSION")"

cd "$PKG_DIR"
# design/design-tokens.json is the canonical shared spec; embed it as Swift source
# (no resource bundle → no CFBundle lookup at launch).
python3 - <<'EOF'
import json, pathlib
src = pathlib.Path("../design/design-tokens.json").read_text()
json.loads(src)  # validate
out = '// GENERATED from design/design-tokens.json by scripts/build-app.sh — do not edit.\n'
out += 'enum DesignTokensData {\n    static let json = #"""\n%s\n"""#\n}\n' % src.rstrip()
pathlib.Path("Sources/AgentTimeline/UI/DesignTokensData.swift").write_text(out)
EOF

# design/strings.json 同理：双端共享文案表，编译进二进制而不是走资源包。
# ⚠ 原样嵌入，不要重新格式化 JSON——CI 门禁（scripts/check-strings.py 第 6 项）
# 断言的是「源文件内容 rstrip 后原样出现在 StringsData.swift 里」。
python3 - <<'EOF'
import json, pathlib
src = pathlib.Path("../design/strings.json").read_text()
json.loads(src)  # validate
out = '// GENERATED from design/strings.json by scripts/build-app.sh — do not edit.\n'
out += 'enum StringsData {\n    static let json = #"""\n%s\n"""#\n}\n' % src.rstrip()
pathlib.Path("Sources/AgentTimeline/UI/StringsData.swift").write_text(out)
EOF
swift build -c "$CONFIG"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$BUILD_DIR/$APP_NAME" "$APP/Contents/MacOS/"
# App icon: committed binary generated by scripts/gen-icon.swift (see macos/Assets/).
cp "$PKG_DIR/Assets/AppIcon.icns" "$APP/Contents/Resources/"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>AgentTimeline</string>
    <key>CFBundleIdentifier</key>
    <string>com.litianyi.agent-timeline</string>
    <key>CFBundleName</key>
    <string>Agent Timeline</string>
    <key>CFBundleDisplayName</key>
    <string>Agent Timeline</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleShortVersionString</key>
    <string>${VERSION}</string>
    <key>CFBundleVersion</key>
    <string>${VERSION}</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHumanReadableCopyright</key>
    <string>© 2026 litianyi</string>
</dict>
</plist>
PLIST

codesign --force --sign - "$APP" 2>/dev/null || true
echo "Built: $APP"
echo "Run:   open \"$APP\""
